name: Brewski
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  Home: /
  About: /about
  Archives: /archives
  #Impressum:
  GitHub: https://github.com/datoga
  RSS: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname
disqus: david-torres

# Analytics
google_analytics: UA-27802531-3

# Copyright Infomation
copyright:
  since: 
  name: David Torres
  url: http://datoga.es
